branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- pelican /home/travis/build/ultramar/ultramar.github.io-source/content -o /home/travis/build/ultramar/ultramar.github.io-source/output -s /home/travis/build/ultramar/ultramar.github.io-source/publishconf.py 
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: lRXjvcO3aBXM+I86YLhVIciwjCQt5MaN9rsRQPE283eyjAgQi2I/9ZRE9SHw67QDx55iYBuoxKjSreVb6GDbxprh4IuByWGZwVtQmuMmtLHKT6PgDXJTpDUaJoR1JkviQRrMfteMDV1bYLFgRIN1vnZDd5UGIQ7Re+cEp/vutEM=
before_install:
- git submodule update --init --recursive
- sudo apt-get install locales
after_success: ./deploy.sh
